
// (c) 2026 Kazuki Kohzuki

using Dirge.Utils;

namespace Dirge.TestGenerator.CodeFixes;

[Generator(LanguageNames.CSharp)]
internal sealed class CodeFixTestGenerator : IIncrementalGenerator
{
    private const string RootAttributeFullName = $"{TypesGenerator.Namespace}.{TypesGenerator.CodeFixTestAttributeName}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sources = context.SyntaxProvider.ForAttributeWithMetadataName(
            RootAttributeFullName,
            static (node, token) => node is ClassDeclarationSyntax,
            static (context, token) => context
        );

        context.RegisterSourceOutput(sources, Execute);
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    private static void Execute(SourceProductionContext context, GeneratorAttributeSyntaxContext provider)
    {
        var typeSymbol = (INamedTypeSymbol)provider.TargetSymbol;

        var attribute = provider.Attributes.FirstOrDefault(attr => attr.AttributeClass?.FullName == RootAttributeFullName);
        if (attribute is null) return;

        var fields =
            typeSymbol.GetMembers()
                      .OfType<IFieldSymbol>()
                      .SelectNotNull(CodeFixSourceInfo.FromFieldSymbol)
                      .ToArray();
        if (fields.Length == 0) return;

        var ns = typeSymbol.ContainingNamespace.ToDisplayString();

        var builder = new StringBuilder();
        builder.Append($$"""
// <auto-generated/>

namespace {{ns}};

partial class {{typeSymbol.Name}}
{
""");

        foreach (var field in fields)
            GenerateTestMethod(builder, field);

        builder.AppendLine("""
            }
            """);

        builder.AppendLine(GeneratorCodeFixTestSource);

        context.AddSource($"{typeSymbol.Name}.GeneratedTests.g.cs", builder.ToString());
    } // private static void Execute(SourceProductionContext context, GeneratorAttributeSyntaxContext provider)

    private static void GenerateTestMethod(StringBuilder builder, CodeFixSourceInfo testCase)
    {
        var sources = new DiffSources(testCase.Source);
        var beforeCode = sources.Before;
        var afterCode = sources.After;

        var beforeDelimiter = new string('"', GetDelimiterCount(beforeCode));
        var afterDelimiter = new string('"', GetDelimiterCount(afterCode));

        var testMethodName = testCase.GetTestMethodName();
        builder.AppendLine($$""""

                [global::Xunit.Fact]
                async internal global::System.Threading.Tasks.Task {{testMethodName}}()
                {
                    // lang=C#
                    var before = {{beforeDelimiter}}
            {{beforeCode}}
            {{beforeDelimiter}};

                    // lang=C#
                    var after = {{afterDelimiter}}
            {{afterCode}}
            {{afterDelimiter}};

                    var test = new Dirge.Test.CodeFixes.GeneratorCodeFixTest<{{testCase.CodeFixType}}>()
                    {
                        TestCode = before,
                        FixedCode = after,
                    };

                    await test.RunAsync(global::Xunit.TestContext.Current.CancellationToken);
                }
            """");
    } // private static void GenerateTestMethod(StringBuilder, TestCaseInfo)

    private static int GetDelimiterCount(string text, char delimiter = '"')
    {
        var maxQuotes = 0;
        var currentQuotes = 0;

        foreach (var c in text)
        {
            if (c == delimiter)
            {
                currentQuotes++;
                if (currentQuotes > maxQuotes)
                {
                    maxQuotes = currentQuotes;
                }
            }
            else
            {
                currentQuotes = 0;
            }
        }

        return Math.Max(maxQuotes + 1, 3);
    } // private static int GetDelimiterCount(string text, char delimiter = '"')

    // lang=C#
    private const string GeneratorCodeFixTestSource = """
        
        file sealed class GeneratorCodeFixTest<TCodeFix> : global::Microsoft.CodeAnalysis.CSharp.Testing.CSharpCodeFixTest<global::Microsoft.CodeAnalysis.Testing.EmptyDiagnosticAnalyzer, TCodeFix, global::Microsoft.CodeAnalysis.Testing.DefaultVerifier>
            where TCodeFix : global::Microsoft.CodeAnalysis.CodeFixes.CodeFixProvider, new()
        {
            protected override global::System.Collections.Generic.IEnumerable<global::System.Type> GetSourceGenerators()
            {
                yield return typeof(global::Dirge.Generators.DisposeGenerator);
                yield return typeof(global::Dirge.Generators.TypesGenerator);
            }

            public GeneratorCodeFixTest()
            {
                this.TestBehaviors = global::Microsoft.CodeAnalysis.Testing.TestBehaviors.SkipGeneratedSourcesCheck;
            }
        }
        """;
} // internal sealed class CodeFixTest : IIncrementalGenerator
