
// (c) 2026 Kazuki Kohzuki

namespace Dirge.TestGenerator.CodeFixes;

[Generator(LanguageNames.CSharp)]
internal sealed class TypesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(context =>
        {
            context.AddSource("CodeFixTestAttribute.g.cs", CodeFixTestAttributeSource);
            context.AddSource("CodeFixSourceAttribute.g.cs", CodeFixSourceAttributeSource);
        });
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    internal const string Namespace = "Dirge.Test.CodeFixes";
    internal const string CodeFixTestAttributeName = "CodeFixTestAttribute";
    internal const string CodeFixSourceAttributeName = "CodeFixSourceAttribute";

    // lang=C#
    private const string CodeFixTestAttributeSource = """
// <auto-generated/>
        
#nullable enable

namespace Dirge.Test.CodeFixes;

[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
internal sealed class CodeFixTestAttribute : global::System.Attribute
{
    internal CodeFixTestAttribute() { }
}
""";

    // lang=C#
    private const string CodeFixSourceAttributeSource = """
// <auto-generated/>
        
#nullable enable

namespace Dirge.Test.CodeFixes;

/// <summary>
/// Indicates that the attributed field provides a code fix to be teste.
/// </summary>
/// <typeparam name="TCodeFix">The type of the code fix provider.</typeparam>
[global::System.AttributeUsage(global::System.AttributeTargets.Field, AllowMultiple = false)]
internal sealed class CodeFixSourceAttribute<TCodeFix> : global::System.Attribute
    where TCodeFix : global::Microsoft.CodeAnalysis.CodeFixes.CodeFixProvider, new()
{
    public string? TestName { get; set; }

    internal CodeFixSourceAttribute() { }
}
""";
} // internal sealed class TypesGenerator
