// <auto-generated/>

#pragma warning disable CS0282

namespace Test
{
    ref partial struct MyStruct
    {
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
        [global::System.Runtime.CompilerServices.CompilerGenerated]
        private bool __generated_disposed = false;

        public void Dispose()
        {
            if (this.__generated_disposed) return;

            try
            {
                this._disposable.Dispose();
            }
            finally
            {
                this.__generated_disposed = true;
            }
        }
    }
}
