
// (c) 2026 Kazuki Kohzuki

using Dirge.Diagnostics;

namespace Dirge.Generators;

[Generator(LanguageNames.CSharp)]
internal sealed class DisposeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sources = context.SyntaxProvider.ForAttributeWithMetadataName(
            TypesGenerator.AutoDisposeAttributeName,
            static (node, token) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
            static (context, token) => DisposableTypeInfo.Create(context)
        );

        context.RegisterSourceOutput(sources, Execute);
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    private static void Execute(SourceProductionContext context, Result<DisposableTypeInfo>? result)
    {
        if (result is null) return;

        if (result.Diagnostic is { } diagnostics)
        {
            foreach (var diagnostic in diagnostics)
                context.ReportDiagnostic(diagnostic);
            return;
        }

        var source = result.Value!;
        var fields = source.Fields;

        var releaseUnmanagedResources = source.ReleaseUnmanagedResources;
        if (fields.Length == 0 && string.IsNullOrEmpty(releaseUnmanagedResources)
            && (source.AsyncGenerationInfo is null || source.AsyncGenerationInfo.OverrideCore))
            return; // Inherit existing implementations when there is no additional cleanup.

        var declarationStack = source.DeclarationStack;

        var isGlobalNamespace = source.NamespaceName is null;
        var namespaceName = source.NamespaceName;

        var builder = new CodeBuilder();
        builder.AppendLine("""
            // <auto-generated/>

            #pragma warning disable CS0282

            """);

        if (!isGlobalNamespace)
        {
            builder.AppendLine($$"""
            namespace {{namespaceName}}
            {
            """);
            builder.Indent();
        }

        for (var i = 0; i < declarationStack.Length; i++)
        {
            var d = declarationStack.Length - 1 - i;
            builder.Append(declarationStack[d].GetDeclaration());
            if (d == 0 && !source.IsRefLikeType) // Do not implement IDisposable for ref structs regardless of the language version
                builder.AppendLine(source.AsyncGenerationInfo is null
                    ? " : global::System.IDisposable"
                    : " : global::System.IDisposable, global::System.IAsyncDisposable");
            else
                builder.AppendLine();
            builder.AppendLine("{");
            builder.Indent();
        }

        builder.AppendLine("""
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            [global::System.Runtime.CompilerServices.CompilerGenerated]
            private bool __generated_disposed = false;

            """);

        DisposeGenerationCore.Generate(builder, source);
        if (source.AsyncGenerationInfo is not null)
            AsyncDisposeGenerationCore.Generate(builder, source);

        for (var i = 0; i < declarationStack.Length; i++)
        {
            builder.Unindent();
            builder.AppendLine("}");
        }

        if (!isGlobalNamespace)
        {
            builder.Unindent();
            builder.AppendLine("}");
        }

        context.AddSource($"{source.Name}.GeneratedDispose.g.cs", builder.ToString());
    } // private static void Execute (SourceProductionContext, GeneratorAttributeSyntaxContext)
} // internal sealed class DisposeGenerator : IIncrementalGenerator
