
// (c) 2026 Kazuki Kohzuki

using Dirge.Utils;
using System.Collections.Generic;

namespace Dirge.Generators;

[Generator(LanguageNames.CSharp)]
internal sealed class DisposeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sources = context.SyntaxProvider.ForAttributeWithMetadataName(
            TypesGenerator.AutoDisposeAttributeName,
            static (node, token) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
            static (context, token) => context
        );

        context.RegisterSourceOutput(sources, Execute);
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    private static void Execute(SourceProductionContext context, GeneratorAttributeSyntaxContext source)
    {
        var compilation = source.SemanticModel.Compilation;
        var disposableSymbol = compilation.GetTypeByMetadataName("System.IDisposable");
        if (disposableSymbol is null) return;

        var targetSymbol = (INamedTypeSymbol)source.TargetSymbol;
        if (targetSymbol.IsReadOnly) return; // TODO: report diagnostic for unsupported types
        
        var isPartial = targetSymbol.DeclaringSyntaxReferences
            .Select(r => r.GetSyntax())
            .OfType<TypeDeclarationSyntax>()
            .Any(s => s.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)));
        if (!isPartial) return; // TODO: report diagnostic for non-partial types

        var attribute = targetSymbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == TypesGenerator.AutoDisposeAttributeName);
        if (attribute is null) return;

        var fields = targetSymbol.GetMembers()
            .OfType<IFieldSymbol>()
            .SelectNotNull(f => DisposableFieldInfo.Create(f, targetSymbol, disposableSymbol, compilation))
            .ToArray();

        if (fields.Length == 0) return;

        var isSealed = targetSymbol.IsSealed;
        var hasDisposableBase = targetSymbol.ImplementsInterface(disposableSymbol);
        if (!attribute.TryGetNamedArgumentValue("ReleaseUnmanagedResources", out string? releaseUnmanagedResources))
            releaseUnmanagedResources = null;

        var canBeSimple =
            isSealed
            && !hasDisposableBase
            && releaseUnmanagedResources is null;

        var declarationStack = GetDeclarationStack(targetSymbol);

        var isGlobalNamespace = targetSymbol.ContainingNamespace.IsGlobalNamespace;
        var namespaceName = targetSymbol.ContainingNamespace.ToDisplayString();

        var builder = new CodeBuilder();
        builder.AppendLine("""
            // <auto-generated/>

            #pragma warning disable CS0282

            """);

        if (!isGlobalNamespace)
        {
            builder.AppendLine($$"""
            namespace {{namespaceName}}
            {
            """);
            builder.Indent();
        }

        var indentOffset = isGlobalNamespace ? 0 : 1;
        for (var i = 0; i < declarationStack.Count; i++)
        {
            var d = declarationStack.Count - 1 - i;
            builder.Append(declarationStack[d].GetDeclaration());
            if (d == 0 && !targetSymbol.IsRefLikeType) // Do not implement IDisposable for ref structs regardless of the language version
                builder.AppendLine(" : global::System.IDisposable");
            else
                builder.AppendLine();
            builder.AppendLine("{");
            builder.Indent();
        }

        builder.AppendLine("""
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            [global::System.Runtime.CompilerServices.CompilerGenerated]
            private bool __generated_disposed = false;

            """);

        if (canBeSimple)
        {
            DisposeGenerationCore.GenerateSimpleDispose(builder, fields);
        }
        else
        {
            var generation = DisposeGenerationInfo.Create(targetSymbol, disposableSymbol, compilation);
            if (generation is null) return; // No need to report diagnostic

            if (generation.Strategy == DisposeGenerationStrategy.GenerateRoot)
                DisposeGenerationCore.GenerateRoot(builder, false, isSealed, fields, targetSymbol.Name, releaseUnmanagedResources);
            else if (generation.Strategy == DisposeGenerationStrategy.OverrideDispose)
                DisposeGenerationCore.GenerateRoot(builder, true, isSealed, fields, targetSymbol.Name, releaseUnmanagedResources);
            else if (generation.Strategy == DisposeGenerationStrategy.OverrideDisposeBool)
                DisposeGenerationCore.GenerateOverrideDisposeBool(builder, generation.AccessModifier, fields, targetSymbol.Name, releaseUnmanagedResources);
        }

        for (var i = 0; i < declarationStack.Count; i++)
        {
            builder.Unindent();
            builder.AppendLine("}");
        }

        if (!isGlobalNamespace)
        {
            builder.Unindent();
            builder.AppendLine("}");
        }

        context.AddSource($"{targetSymbol.Name}.GeneratedDispose.g.cs", builder.ToString());
    } // private static void Execute (SourceProductionContext, GeneratorAttributeSyntaxContext)

    private static List<TypeWrapperInfo> GetDeclarationStack(INamedTypeSymbol symbol)
    {
        var stack = new List<TypeWrapperInfo>();

        while (symbol is not null)
        {
            var info = TypeWrapperInfo.FromTypeSymbol(symbol);
            if (info is null)
                break;
            stack.Add(info);
            symbol = symbol.ContainingType;
        }

        return stack;
    } // private static List<TypeWrapperInfo> GetDeclarationStack (INamedTypeSymbol)
} // internal sealed class DisposeGenerator : IIncrementalGenerator
