
// (c) 2026 Kazuki Kohzuki

namespace Dirge.Generators;

[Generator(LanguageNames.CSharp)]
internal sealed class TypesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("AutoDisposeAttribute.g.cs", AutoDisposeAttributeSource);
            ctx.AddSource("DoNotDisposeAttribute.g.cs", DoNotDisposeAttributeSource);
            ctx.AddSource("DoNotDisposeWhenAttribute.g.cs", DoNotDisposeWhenAttributeSource);
        });
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    internal const string AutoDisposeAttributeName = "Dirge.AutoDisposeAttribute";
    internal const string DoNotDisposeAttributeName = "Dirge.DoNotDisposeAttribute";
    internal const string DoNotDisposeWhenAttributeName = "Dirge.DoNotDisposeWhenAttribute";

    // lang=C#
    private const string AutoDisposeAttributeSource = """
// <auto-generated />

#nullable enable

namespace Dirge
{
    /// <summary>
    /// Generates IDisposable implementation for a partial class or struct.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
    internal sealed class AutoDisposeAttribute : global::System.Attribute
    {
        /// <summary>
        /// Also generates asynchronous disposal for a partial class.
        /// </summary>
        public bool IncludeAsync { get; set; } = false;

        /// <summary>
        /// The name of the method that releases unmanaged resources. If not specified, no finalizer will be generated.
        /// </summary>
        public string? ReleaseUnmanagedResources { get; set; } = null;

        internal AutoDisposeAttribute() { }
    }
}
""";

    // lang=C#
    private const string DoNotDisposeAttributeSource = """
// <auto-generated />

namespace Dirge
{
    /// <summary>
    /// Marks a field to be excluded from the generated IDisposable implementation.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
    internal sealed class DoNotDisposeAttribute : global::System.Attribute
    {
        internal DoNotDisposeAttribute() { }
    }
}
""";

    // lang=C#
    private const string DoNotDisposeWhenAttributeSource = """
// <auto-generated />

namespace Dirge
{
    /// <summary>
    /// Marks a field to be excluded from the generated IDisposable implementation when a specified boolean flag is set to a certain value.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
    internal sealed class DoNotDisposeWhenAttribute : global::System.Attribute
    {
        /// <summary>
        /// The name of the boolean flag.
        /// </summary>
        internal string FlagName { get; }

        /// <summary>
        /// The condition the boolean flag must be set to.
        /// </summary>
        internal bool FlagCondition { get; }

        internal DoNotDisposeWhenAttribute(string flagName, bool flagCondition)
        {
            this.FlagName = flagName;
            this.FlagCondition = flagCondition;
        }
    }
}
""";
} // internal sealed class TypesGenerator : IIncrementalGenerator
