
// (c) 2026 Kazuki Kohzuki

namespace Dirge.Generators;

[Generator(LanguageNames.CSharp)]
internal sealed class TypesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("AutoDisposeAttribute.g.cs", AutoDisposeAttributeSource);
            ctx.AddSource("DoNotDisposeAttribute.g.cs", DoNotDisposeAttributeSource);
            ctx.AddSource("DoNotDisposeWhenAttribute.g.cs", DoNotDisposeWhenAttributeSource);
        });
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    internal const string AutoDisposeAttributeName = "Dirge.AutoDisposeAttribute";
    internal const string DoNotDisposeAttributeName = "Dirge.DoNotDisposeAttribute";
    internal const string DoNotDisposeWhenAttributeName = "Dirge.DoNotDisposeWhenAttribute";

    // lang=C#
    private const string AutoDisposeAttributeSource = """
// <auto-generated />

#nullable enable

namespace Dirge
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
    internal sealed class AutoDisposeAttribute : global::System.Attribute
    {
        public string? ReleaseUnmanagedResources { get; set; } = null;

        internal AutoDisposeAttribute() { }
    }
}
""";

    // lang=C#
    private const string DoNotDisposeAttributeSource = """
// <auto-generated />

namespace Dirge
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
    internal sealed class DoNotDisposeAttribute : global::System.Attribute
    {
        internal DoNotDisposeAttribute() { }
    }
}
""";

    // lang=C#
    private const string DoNotDisposeWhenAttributeSource = """
// <auto-generated />

namespace Dirge
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
    internal sealed class DoNotDisposeWhenAttribute : global::System.Attribute
    {
        internal string FlagName { get; }

        internal bool FlagCondition { get; }

        internal DoNotDisposeWhenAttribute(string flagName, bool flagCondition)
        {
            this.FlagName = flagName;
            this.FlagCondition = flagCondition;
        }
    }
}
""";
} // internal sealed class TypesGenerator : IIncrementalGenerator
