
// (c) 2026 Kazuki Kohzuki

namespace Dirge.TestGenerator.Verify;

[Generator(LanguageNames.CSharp)]
internal sealed class TypesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource("VerifyTestAttribute.g.cs", VerifyTestAttributeSource);
        });
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    internal const string Namespace = "Dirge.Test.Verify";
    internal const string VerifyTestAttribute = "VerifyTestAttribute";

    // lang=C#
    private const string VerifyTestAttributeSource = """
// <auto-generated/>
        
#nullable enable

namespace Dirge.Test.Verify;

[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
internal sealed class VerifyTestAttribute : global::System.Attribute
{
    internal global::System.Collections.Generic.IReadOnlyList<global::Microsoft.CodeAnalysis.CSharp.LanguageVersion> LanguageVersions { get; }

    internal VerifyTestAttribute(params global::Microsoft.CodeAnalysis.CSharp.LanguageVersion[] languageVersions)
    {
        this.LanguageVersions = languageVersions;
    }
}
""";
} // internal sealed class TypesGenerator : IIncrementalGenerator
