// <auto-generated/>

#pragma warning disable CS0282

partial class Owner<__generated_disposed> : global::System.IDisposable, global::System.IAsyncDisposable
{
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    private bool __generated_disposed_2 = false;

    public void Dispose()
    {
        Dispose(true);
        global::System.GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool disposing)
    {
        if (this.__generated_disposed_2) return;

        try
        {
            if (disposing)
            {
                if (this.@__generated_asyncDisposed is global::System.IDisposable __generated_sync___generated_asyncDisposed)
                {
                    __generated_sync___generated_asyncDisposed.Dispose();
                }
            }
        }
        finally
        {
            this.__generated_disposed_2 = true;
        }
    }

    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    private bool __generated_asyncDisposed_3 = false;

    public async global::System.Threading.Tasks.ValueTask DisposeAsync()
    {
        if (this.__generated_disposed_2) return;

        try
        {
            await DisposeAsyncCore().ConfigureAwait(false);
        }
        finally
        {
            Dispose(false);
            global::System.GC.SuppressFinalize(this);
        }
    }

    protected virtual async global::System.Threading.Tasks.ValueTask DisposeAsyncCore()
    {
        if (this.__generated_disposed_2 || this.__generated_asyncDisposed_3) return;

        try
        {
            if (this.@__generated_asyncDisposed is not null)
            {
                await this.@__generated_asyncDisposed.DisposeAsync().ConfigureAwait(false);
            }
        }
        finally
        {
            this.__generated_asyncDisposed_3 = true;
        }
    }
}
