
// (c) 2026 Kazuki Kohzuki

using Dirge.Utils;

namespace Dirge.TestGenerator.IntegrationTest;

[Generator(LanguageNames.CSharp)]
internal sealed class IntegrationTestGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sources = context.SyntaxProvider.ForAttributeWithMetadataName(
            TypesGenerator.TestClassAttributeFullName,
            static (node, token) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
            static (context, toekn) => context
        );

        context.RegisterSourceOutput(sources, Execute);
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    private static readonly string[] _requiredKeywords = [
        "static", "abstract", "sealed", "readonly", "ref"
    ];

    private static void Execute(SourceProductionContext context, GeneratorAttributeSyntaxContext provider)
    {
        var typeSymbol = (INamedTypeSymbol)provider.TargetSymbol;

        if (typeSymbol.DeclaringSyntaxReferences.FirstOrDefault() is not { } syntaxReference) return;
        if (syntaxReference.GetSyntax() is not TypeDeclarationSyntax typeDeclaration) return;

        var modifiers = typeDeclaration.Modifiers
            .Select(m => m.ValueText)
            .Where(keyword => _requiredKeywords.Contains(keyword));

        var modifiersString = string.Join(" ", modifiers);
        if (!string.IsNullOrEmpty(modifiersString))
        {
            modifiersString += " ";
        }

        var keyword = typeDeclaration.Keyword.ValueText;

        var attribute = provider.Attributes.FirstOrDefault(attr => attr.AttributeClass?.FullName == TypesGenerator.TestClassAttributeFullName);
        if (attribute is null) return;

        var disposedFields = GetFieldNames(attribute, "DisposedFields");
        var notDisposedFields = GetFieldNames(attribute, "NotDisposedFields");

        if (!attribute.TryGetNamedArgumentValue("Name", out string? testName) || string.IsNullOrEmpty(testName))
            testName = $"{typeSymbol.Name}Test";

        var fullName = typeSymbol.FullyQualifiedName;
        var ns = typeSymbol.ContainingNamespace.ToDisplayString();

        var builder = new StringBuilder();
        builder.AppendLine($$"""
// <auto-generated/>

namespace {{ns}};

{{modifiersString}}partial {{keyword}} {{typeSymbol.Name}}
{
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public static class Test
    {
        [global::Xunit.Fact(DisplayName = "{{testName}}")]
        public static void Run()
        {
            {{fullName}} target = new();

            target.Dispose();
            target.Dispose(); // Call Dispose twice to check if it can be called multiple times.
""");
        if (disposedFields.Length > 0)
        {
            builder.AppendLine();
            foreach (var field in disposedFields)
                builder.AppendLine($"            global::Xunit.Assert.True(target.{field}.IsDisposed);");
        }

        if (notDisposedFields.Length > 0)
        {
            builder.AppendLine();
            foreach (var field in notDisposedFields)
                builder.AppendLine($"            global::Xunit.Assert.False(target.{field}.IsDisposed);");
        }

        builder.AppendLine("""
                    }
                }
            }
            """);

        context.AddSource($"{typeSymbol.Name}.IntegrationTest.g.cs", builder.ToString());
    } // private static void Execute (SourceProductionContext, GeneratorAttributeSyntaxContext)

    private static string[] GetFieldNames(AttributeData attribute, string argumentName)
    {
        foreach (var namedArg in attribute.NamedArguments)
        {
            if (namedArg.Key != argumentName) continue;
            if (namedArg.Value.Kind != TypedConstantKind.Array) return [];
            if (namedArg.Value.IsNull) return [];
            return [.. namedArg.Value.Values
                .Where(v => v.Kind == TypedConstantKind.Primitive && v.Value is string)
                .Select(v => (string)v.Value!)];
        }
        return [];
    } // private static string[] GetFieldNames (AttributeData, string)
} // internal sealed class IntegrationTestGenerator : IIncrementalGenerator
