
// (c) 2026 Kazuki Kohzuki

namespace Dirge.TestGenerator.IntegrationTest;

[Generator(LanguageNames.CSharp)]
internal sealed class TypesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("TestClassAttribute.g.cs", TestClassAttribute);
        });
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    internal const string TestClassAttributeFullName = "Dirge.Test.IntegrationTest.TestClassAttribute";

    // lang=C#
    private const string TestClassAttribute = """
        // <auto-generated />

        #nullable enable

        namespace Dirge.Test.IntegrationTest;

        [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = false)]
        internal sealed class TestClassAttribute : global::System.Attribute
        {
            public string? Name { get; set; } = null;
            public string[]? DisposedFields { get; set; }
            public string[]? NotDisposedFields { get; set; }

            internal TestClassAttribute() { }
        }
        """;
} // internal sealed class TypesGenerator : IIncrementalGenerator
