// <auto-generated/>

#pragma warning disable CS0282

sealed partial class Owner : global::System.IDisposable
{
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    private bool __generated_disposed_4 = false;

    public void Dispose()
    {
        if (this.__generated_disposed_4) return;

        try
        {
            this.__generated_disposed?.Dispose();
        }
        finally
        {
            this.__generated_disposed_4 = true;
        }
    }
}
