
// (c) 2026 Kazuki Kohzuki

namespace Dirge.SourceGeneratorUtils;

[Generator(LanguageNames.CSharp)]
internal sealed class SpanBuilder : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(context =>
        {
            context.AddSource("SpanBuilder.g.cs", Source);
        });
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    // lang=C#
    private const string Source = """
        // <auto-generated/>

        namespace Dirge.Utils;

        internal ref struct SpanBuilder<T>
        {
            private global::System.Span<T> _buffer;
            private int _length;

            readonly internal int Length => this._length;

            readonly internal global::System.ReadOnlySpan<T> AsSpan() => this._buffer[..this._length];

            internal SpanBuilder(global::System.Span<T> buffer)
            {
                this._buffer = buffer;
                this._length = 0;
            }

            internal void Append(T item)
            {
                if (this._length >= this._buffer.Length)
                    throw new global::System.InvalidOperationException("Buffer overflow");

                this._buffer[this._length++] = item;
            }

            internal void Append(global::System.ReadOnlySpan<T> span)
            {
                if (this._length + span.Length > this._buffer.Length)
                    throw new global::System.InvalidOperationException("Buffer overflow");

                span.CopyTo(this._buffer[this._length..]);
                this._length += span.Length;
            }
        }

        internal static class SpanBuilderExtensions
        {
            extension (ref global::Dirge.Utils.SpanBuilder<char> builder)
            {
                internal void AppendLine()
                {
                    builder.Append('\r');
                    builder.Append('\n');
                }

                internal void AppendLine(global::System.ReadOnlySpan<char> line)
                {
                    builder.Append(line);
                    builder.AppendLine();
                }
            }
        }
        """;
} // internal sealed class SpanBuilder
