
// (c) 2026 Kazuki Kohzuki

namespace Dirge.SourceGeneratorUtils;

[Generator(LanguageNames.CSharp)]
internal sealed class TypeSymbolExtensions : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource("TypeSymbolExtensions.g.cs", Source));
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    // lang=C#
    private const string Source = """
// <auto-generated/>

using System.Collections.Generic;

namespace Dirge.Utils;

internal static class TypeSymbolExtensions
{
    extension (global::Microsoft.CodeAnalysis.ITypeSymbol symbol)
    {
        #region name

        /// <summary>
        /// Gets the fully qualified name of the symbol, excluding the global namespace prefix.
        /// </summary>
        internal string FullName
            => symbol.ToDisplayString(global::Microsoft.CodeAnalysis.SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(global::Microsoft.CodeAnalysis.SymbolDisplayGlobalNamespaceStyle.Omitted));

        /// <summary>
        /// Gets the fully qualified name of the symbol, including the global namespace.
        /// </summary>
        internal string FullyQualifiedName
            => symbol.ToDisplayString(global::Microsoft.CodeAnalysis.SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(global::Microsoft.CodeAnalysis.SymbolDisplayGlobalNamespaceStyle.Included));

        #endregion name

        #region inheritance

        /// <summary>
        /// Determines whether the symbol implements the specified interface.
        /// </summary>
        /// <param name="interfaceSymbol">The interface symbol to check.</param>
        /// <returns><see langword="true"/> if the symbol implements the interface or is the interface itself; otherwise, <see langword="false"/>.</returns>
        internal bool ImplementsInterface(global::Microsoft.CodeAnalysis.INamedTypeSymbol interfaceSymbol)
        {
            if (global::Microsoft.CodeAnalysis.SymbolEqualityComparer.Default.Equals(symbol.OriginalDefinition, interfaceSymbol))
                return true;

            foreach (var i in symbol.AllInterfaces)
            {
                if (global::Microsoft.CodeAnalysis.SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, interfaceSymbol))
                    return true;
            }

            return false;
        } // internal bool ImplementsInterface (INamedTypeSymbol)

        #endregion inheritance

        internal IEnumerable<global::Microsoft.CodeAnalysis.IFieldSymbol> StaticFields
            => symbol.GetMembers().OfType<global::Microsoft.CodeAnalysis.IFieldSymbol>().Where(f => f.IsStatic);
    }
}
""";
} // internal sealed class TypeSymbolExtensions : IIncrementalGenerator
