// <auto-generated/>

#pragma warning disable CS0282

partial class Owner : global::System.IDisposable, global::System.IAsyncDisposable
{
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    private bool __generated_disposed = false;

    public void Dispose()
    {
        Dispose(true);
        global::System.GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool disposing)
    {
        if (this.__generated_disposed) return;

        try
        {
            if (disposing)
            {
                this.@_sync?.Dispose();
                this.@_dual?.Dispose();
            }
        }
        finally
        {
            this.__generated_disposed = true;
        }
    }

    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    private bool __generated_asyncDisposed = false;

    public async global::System.Threading.Tasks.ValueTask DisposeAsync()
    {
        if (this.__generated_disposed) return;

        try
        {
            await DisposeAsyncCore().ConfigureAwait(false);
        }
        finally
        {
            Dispose(false);
            global::System.GC.SuppressFinalize(this);
        }
    }

    protected virtual async global::System.Threading.Tasks.ValueTask DisposeAsyncCore()
    {
        if (this.__generated_disposed || this.__generated_asyncDisposed) return;

        try
        {
            this.@_sync?.Dispose();
            if (this.@_dual is not null)
            {
                await this.@_dual.DisposeAsync().ConfigureAwait(false);
            }
            await this.@_value.DisposeAsync().ConfigureAwait(false);
            if (this.@_nullableValue.HasValue)
            {
                await this.@_nullableValue.Value.DisposeAsync().ConfigureAwait(false);
            }
            if (this.@_explicit is not null)
            {
                await ((global::System.IAsyncDisposable)this.@_explicit).DisposeAsync().ConfigureAwait(false);
            }
        }
        finally
        {
            this.__generated_asyncDisposed = true;
        }
    }
}
