
// (c) 2026 Kazuki Kohzuki

namespace Dirge.TestGenerator;

[Generator(LanguageNames.CSharp)]
internal sealed class TestSourceAttributeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource("TestSourceAttribute.g.cs", TestSourceAttributeSource));
    }

    internal const string Namespace = "Dirge.Test";
    internal const string TestSourceAttribute = "TestSourceAttribute";

    // lang=C#
    private const string TestSourceAttributeSource = """
// <auto-generated/>
        
#nullable enable

namespace Dirge.Test;

[global::System.AttributeUsage(global::System.AttributeTargets.Field, AllowMultiple = false)]
internal sealed class TestSourceAttribute : global::System.Attribute
{
    public string? TestName { get; set; }

    internal TestSourceAttribute() { }
}
""";
}
