// <auto-generated/>

#pragma warning disable CS0282

namespace Test
{
    sealed partial class MyClass : global::System.IDisposable
    {
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
        [global::System.Runtime.CompilerServices.CompilerGenerated]
        private bool __generated_disposed = false;

        override public void Dispose()
        {
            Dispose(true);
        }

        private void Dispose(bool disposing)
        {
            if (this.__generated_disposed) return;

            try
            {
                if (disposing)
                {
                    this._stream?.Dispose();
                }
            }
            finally
            {
                this.__generated_disposed = true;
            }
        }
    }
}
