
// (c) 2026 Kazuki Kohzuki

using Dirge.Utils;

namespace Dirge.TestGenerator.Diagnostics;

[Generator]
internal sealed class DiagnosticTestGenerator : IIncrementalGenerator
{
    private const string RootAttributeFullName = $"{TypesGenerator.Namespace}.{TypesGenerator.DiagnosticTestAttributeName}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sources = context.SyntaxProvider.ForAttributeWithMetadataName(
            RootAttributeFullName,
            static (node, token) => node is ClassDeclarationSyntax,
            static (context, toekn) => context
        );

        context.RegisterSourceOutput(sources, Execute);
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    private static void Execute(SourceProductionContext context, GeneratorAttributeSyntaxContext provider)
    {
        var typeSymbol = (INamedTypeSymbol)provider.TargetSymbol;

        var attribute = provider.Attributes.FirstOrDefault(attr => attr.AttributeClass?.FullName == RootAttributeFullName);
        if (attribute is null) return;

        var fields =
            typeSymbol.GetMembers()
                      .OfType<IFieldSymbol>()
                      .SelectNotNull(TestCaseInfo.FromFieldSymbol)
                      .ToArray();
        if (fields.Length == 0) return;

        var ns = typeSymbol.ContainingNamespace.ToDisplayString();

        var builder = new StringBuilder();
        builder.AppendLine($$"""
// <auto-generated/>

namespace {{ns}};

partial class {{typeSymbol.Name}}
{
""");

        foreach (var field in fields)
        {
            var testMethodName = field.GetTestMethodName();

            var mod = field.SourceIsStatic ? string.Empty : "this.";
            builder.AppendLine($$"""

                [global::Xunit.Fact]
                async internal global::System.Threading.Tasks.Task {{testMethodName}}()
                {
                    await new global::{{ns}}.DirgeDiagnosticTest({{mod}}{{field.SourceName}}).RunAsync(global::Xunit.TestContext.Current.CancellationToken);
                }
                """);
        }

        builder.AppendLine("""
            }
            """);

        builder.AppendLine(DirgeDiagnosticTestSource);

        context.AddSource($"{typeSymbol.Name}.GeneratedTests.g.cs", builder.ToString());
    } // private static void Execute (SourceProductionContext, GeneratorAttributeSyntaxContext)

    // lang=C#
    private const string DirgeDiagnosticTestSource = """

        file class DirgeDiagnosticTest : global::Microsoft.CodeAnalysis.CSharp.Testing.CSharpSourceGeneratorTest<
            global::Dirge.Generators.DisposeGenerator,
            global::Microsoft.CodeAnalysis.Testing.DefaultVerifier
        >
        {
            internal DirgeDiagnosticTest(string source)
            {
                this.TestState.Sources.Add(source);
                this.TestState.ReferenceAssemblies = global::Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.Net.Net100;
                this.TestBehaviors = global::Microsoft.CodeAnalysis.Testing.TestBehaviors.SkipGeneratedSourcesCheck;
            }

            override protected global::System.Collections.Generic.IEnumerable<global::System.Type> GetSourceGenerators()
            {
                foreach (var generator in base.GetSourceGenerators())
                    yield return generator;

                yield return typeof(global::Dirge.Generators.TypesGenerator);
            } // override protected IEnumerable<Type> GetSourceGenerators ()
        } // internal class DirgeDiagnosticTest : DiagnosticTest
        """;
} // internal sealed class DiagnosticTestGenerator : IIncrementalGenerator
