
// (c) 2026 Kazuki Kohzuki

namespace Dirge.TestGenerator.Diagnostics;

[Generator(LanguageNames.CSharp)]
internal sealed class TypesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(context =>
        {
            context.AddSource("DiagnosticTestAttribute.g.cs", DiagnosticTestAttributeSource);
        });
    } // public void Initialize (IncrementalGeneratorInitializationContext)

    internal const string Namespace = "Dirge.Test.Diagnostics";
    internal const string DiagnosticTestAttributeName = "DiagnosticTestAttribute";

    // lang=C#
    private const string DiagnosticTestAttributeSource = """
// <auto-generated/>
        
#nullable enable

namespace Dirge.Test.Diagnostics;

[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
internal sealed class DiagnosticTestAttribute : global::System.Attribute
{
    internal DiagnosticTestAttribute() { }
}
""";
} // internal sealed class TypesGenerator
