// <auto-generated/>

#pragma warning disable CS0282

namespace Test
{
    partial class MyClass : global::System.IDisposable
    {
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
        [global::System.Runtime.CompilerServices.CompilerGenerated]
        private bool __generated_disposed = false;

        public void Dispose()
        {
            Dispose(true);
            global::System.GC.SuppressFinalize(this);
        }

        protected virtual void Dispose(bool disposing)
        {
            if (this.__generated_disposed) return;

            try
            {
                if (disposing)
                {
                    this._stream?.Dispose();

                    if (this._leaveOpen1)
                    {
                        this._stream3?.Dispose();
                    }
                    else
                    {
                        this._stream1?.Dispose();
                        this._stream2?.Dispose();
                    }

                    if (_leaveOpen2)
                    {
                        this._stream4?.Dispose();
                    }
                }
            }
            finally
            {
                this.__generated_disposed = true;
            }
        }
    }
}
